apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  replicas: {{ .Values.apiServer.replicaCount }}
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: "{{ .Values.apiServer.image.repository }}:{{ .Values.apiServer.image.tag }}"
        ports:
        - containerPort: {{ .Values.apiServer.service.port }}
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: {{ .Values.apiServer.mongoUriSecret }}
              key: {{ .Values.apiServer.mongoUriKey }}
        - name: KAFKA_BROKER
          value: {{ .Values.apiServer.kafkaBroker }}
