apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-server
  labels:
    app: client-server
spec:
  replicas: {{ .Values.clientServer.replicaCount }}
  selector:
    matchLabels:
      app: client-server
  template:
    metadata:
      labels:
        app: client-server
    spec:
      containers:
      - name: client-server
        image: "{{ .Values.clientServer.image.repository }}:{{ .Values.clientServer.image.tag }}"
        ports:
        - containerPort: {{ .Values.clientServer.service.port }}
        env:
        - name: KAFKA_BROKER
          value: {{ .Values.clientServer.kafkaBroker }}
        - name: API_SERVER_URL
          value: {{ .Values.clientServer.apiServerUrl }}
