apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client-server-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.clientServer.ingress.hosts[0].host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-server-svc
                port:
                  number: {{ .Values.clientServer.service.port }}
