apiVersion: v1
kind: Service
metadata:
  name: client-server-svc
spec:
  selector:
    app: client-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: {{ .Values.clientServer.service.type }}

