image:
  repository: ghcr.io/kuper-s/argo_app
  tag: latest
apiServer:
  replicaCount: 1
  image:
    repository: ghcr.io/kuper-s/argo_app_api
    tag: 840c0faacecafcfd6e2b554c62c5a0c515454e67 # This will be dynamically set by the Flask app
  service:
    type: ClusterIP
    port: 5000
  kafkaBroker: my-kafka-kafka-helm-b.default.svc.cluster.local:9092
  mongoUriSecret: mongo-secret
  mongoUriKey: uri
clientServer:
  replicaCount: 1
  image:
    repository: ghcr.io/kuper-s/argo_app_client
    tag: 840c0faacecafcfd6e2b554c62c5a0c515454e67 # This will be dynamically set by the Flask app
  service:
    type: ClusterIP
    port: 8000
  kafkaBroker: my-kafka-kafka-helm-b.default.svc.cluster.local:9092
  apiServerUrl: http://api-server-svc.default.svc.cluster.local:5000
  ingress:
    enabled: true
    className: nginx
    annotations: {}
    host: client.example.com # This will be dynamically set by the Flask app
    namespace: "" # This will be dynamically set by the Flask app
kafka:
  broker: my-kafka-kafka-helm-b.default.svc.cluster.local:9092
